import type { PersonaConfig } from '../types';

export const PERSONAS: PersonaConfig[] = [
  {
    id: 'maa',
    nameEn: 'Maa',
    nameHi: 'माँ',
    taglineEn: 'Caring & Nurturing Guide',
    taglineHi: 'प्यार भरी सलाहकार',
    emoji: '💖',
    color: '#FF6B00',
    bgColor: '#FFF0E6',
  },
  {
    id: 'banker',
    nameEn: 'Banker',
    nameHi: 'बैंकर',
    taglineEn: 'Formal Finance Advisor',
    taglineHi: 'औपचारिक वित्त सलाहकार',
    emoji: '💰',
    color: '#1B6B3A',
    bgColor: '#E8F5EE',
  },
  {
    id: 'dost',
    nameEn: 'Dost',
    nameHi: 'दोस्त',
    taglineEn: 'Friendly Companion',
    taglineHi: 'दोस्ताना साथी',
    emoji: '😎',
    color: '#D4A017',
    bgColor: '#F5E6C0',
  },
];

export const I18N = {
  en: {
    appName: 'Lakshmi Didi',
    appTagline: 'Your personal finance companion',
    chooseLanguage: 'Choose your language',
    choosePersona: 'Choose your guide',
    startChat: 'Start Chatting',
    typeMessage: 'Type your question...',
    send: 'Send',
    keyPoints: 'Key Points',
    newChat: 'New Chat',
    history: 'History',
    loading: 'Thinking...',
    welcomeMsg: (persona: string) => `Namaste! I'm your ${persona}. Ask me anything about saving, investing, insurance, or managing money in India.`,
    suggestionLabel: 'Try asking:',
    suggestions: [
      'How should I start investing with ₹5000/month?',
      'What is the best way to save tax in India?',
      'Should I buy term insurance?',
      'How do I build an emergency fund?',
      'What is SIP and how does it work?',
    ],
  },
  hi: {
    appName: 'लक्ष्मी दीदी',
    appTagline: 'आपकी वित्तीय साथी',
    chooseLanguage: 'अपनी भाषा चुनें',
    choosePersona: 'अपना मार्गदर्शक चुनें',
    startChat: 'बात शुरू करें',
    typeMessage: 'अपना सवाल लिखें...',
    send: 'भेजें',
    keyPoints: 'मुख्य बातें',
    newChat: 'नई बात',
    history: 'इतिहास',
    loading: 'सोच रही हूँ...',
    welcomeMsg: (persona: string) => `नमस्ते! मैं आपकी ${persona} हूँ। बचत, निवेश, बीमा या पैसे के बारे में कुछ भी पूछें। `,
    suggestionLabel: 'पूछकर देखें:',
    suggestions: [
      '₹5000/महीने से निवेश कैसे शुरू करूँ?',
      'भारत में टैक्स बचाने का सबसे अच्छा तरीका?',
      'क्या मुझे टर्म इंश्योरेंस लेना चाहिए?',
      'इमरजेंसी फंड कैसे बनाएं?',
      'SIP क्या है और यह कैसे काम करता है?',
    ],
  },
};
